version: "3.9"
services:
  bot:
    container_name: paper-bot
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/bot
  mysql:
    container_name: database
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: example